#声明电影购票微服务的端口号
server:
  port: 8001

#声明微服务的名称
spring:
  application:
    name: microservice-movie

#向eureka服务器注册
eureka:
  client:
    #向eureka服务器注册
    fetch-registry: true
    #向eureka服务器索要信息
    register-with-eureka: true
    #声明eureka注册服务的url
    service-url:
      defaultZone: http://192.168.32.1:8888/eureka
    registry-fetch-interval-seconds: 30
    