#声明微服务的端口号
server:
  port: 9001

#声明微服务的名称
spring:
  application:
    name: microservice-user
  #声明数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.140:3306/jsd21132?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  #声明jpa实施正向工程
  jpa:
    #显示sql语句
    show-sql: true
    #生成建表语句
    generate-ddl: true
    #底层数据库是MySQL数据库
    database: mysql #声明微服务的端口号

#eureka客户端向eureka服务器注册
eureka:
  client:
    #eureka客户端向eureka服务器注册
    register-with-eureka: true
    #向eureka服务器索要信息
    fetch-registry: true
    #注册服务的url
    service-url:
      defaultZone: http://192.168.32.1:8888/eureka

  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90